// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6XyW6Uv_FraB2gs-C5rXg-giWh1NYXqM',
    appId: '1:447140580678:web:24f503e8aed36c56e6a947',
    messagingSenderId: '447140580678',
    projectId: 'easy-rentals-9deaa',
    authDomain: 'easy-rentals-9deaa.firebaseapp.com',
    storageBucket: 'easy-rentals-9deaa.appspot.com',
    measurementId: 'G-YBXYD3QV2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv3c0n1D8AlFYRXpAcHHkwRrcuramwQ1Q',
    appId: '1:447140580678:android:227449480c26cf11e6a947',
    messagingSenderId: '447140580678',
    projectId: 'easy-rentals-9deaa',
    storageBucket: 'easy-rentals-9deaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS809Xui15PGKn-aXFSsAG5Effo8wMhNI',
    appId: '1:447140580678:ios:fa3aa0ec7da6bcd1e6a947',
    messagingSenderId: '447140580678',
    projectId: 'easy-rentals-9deaa',
    storageBucket: 'easy-rentals-9deaa.appspot.com',
    iosBundleId: 'com.example.easyRentals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS809Xui15PGKn-aXFSsAG5Effo8wMhNI',
    appId: '1:447140580678:ios:903a61fc1ce48293e6a947',
    messagingSenderId: '447140580678',
    projectId: 'easy-rentals-9deaa',
    storageBucket: 'easy-rentals-9deaa.appspot.com',
    iosBundleId: 'com.example.easyRentals.RunnerTests',
  );
}
